version: '2'
services:
  dbpostgres:
    image: postgres
    volumes:
      - .:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - homework
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: snikfal@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pguser
    volumes:
       - .:/root/.pgadmin
    ports:
      - "8080:80"
    networks:
      - homework
    restart: unless-stopped

networks:
  homework:
    driver: bridge
