version: '2'
services:
  dbpostgres:
    container_name: postgres_db
    image: postgres
    volumes:
      - .:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - homework
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: snikfal@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pguser
    volumes:
       - .:/root/.pgadmin
    ports:
      - "8080:80"
    networks:
      - homework
    restart: unless-stopped

  python_app:
    build: ./dir
    image: shinik/wiki_ml:latest   
    container_name: ml_application
    volumes:
      - .:/usr/src
    ports:
      -"8888:8888"
    networks:
      - homework
    restart: unless-stopped

